modLoader="kotlinforforge"
loaderVersion="${forge_loader_version}"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    description="${mod_description}"
    authors="Deftu"
    logoFile="icon.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minor_mc_version},)"
    ordering="NONE"
    side="BOTH"
