modLoader="kotlinforforge"
loaderVersion="${forge_loader_version}"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="test-mod"
    version="0.1.0"
    displayName="Test Mod"
    authors="Deftu"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minor_mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="omnicore"
    mandatory=true
    versionRange="[0.8.0]"
    ordering="AFTER"
    side="BOTH"
