modLoader="kotlinforforge"
loaderVersion="${forge_loader_version}"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mods]]
    modId="testmod"
    version="0.1.0"
    displayName="Test Mod"
    authors="Deftu"

[[dependencies.testmod]]
    modId="omnicore"
    mandatory=true
    versionRange="[0.35.0,)"
    ordering="AFTER"
    side="BOTH"
