package dev.deftu.omnicore.api.client.input

import org.lwjgl.glfw.GLFW

public object OmniKeys {
    // --- Special / Unknown ---
    @JvmField public val KEY_NONE: OmniKey = OmniKey(GLFW.GLFW_KEY_UNKNOWN)

    // --- Function Keys ---
    @JvmField public val KEY_ESCAPE: OmniKey = OmniKey(GLFW.GLFW_KEY_ESCAPE)
    @JvmField public val KEY_F1: OmniKey = OmniKey(GLFW.GLFW_KEY_F1)
    @JvmField public val KEY_F2: OmniKey = OmniKey(GLFW.GLFW_KEY_F2)
    @JvmField public val KEY_F3: OmniKey = OmniKey(GLFW.GLFW_KEY_F3)
    @JvmField public val KEY_F4: OmniKey = OmniKey(GLFW.GLFW_KEY_F4)
    @JvmField public val KEY_F5: OmniKey = OmniKey(GLFW.GLFW_KEY_F5)
    @JvmField public val KEY_F6: OmniKey = OmniKey(GLFW.GLFW_KEY_F6)
    @JvmField public val KEY_F7: OmniKey = OmniKey(GLFW.GLFW_KEY_F7)
    @JvmField public val KEY_F8: OmniKey = OmniKey(GLFW.GLFW_KEY_F8)
    @JvmField public val KEY_F9: OmniKey = OmniKey(GLFW.GLFW_KEY_F9)
    @JvmField public val KEY_F10: OmniKey = OmniKey(GLFW.GLFW_KEY_F10)
    @JvmField public val KEY_F11: OmniKey = OmniKey(GLFW.GLFW_KEY_F11)
    @JvmField public val KEY_F12: OmniKey = OmniKey(GLFW.GLFW_KEY_F12)
    @JvmField public val KEY_F13: OmniKey = OmniKey(GLFW.GLFW_KEY_F13)
    @JvmField public val KEY_F14: OmniKey = OmniKey(GLFW.GLFW_KEY_F14)
    @JvmField public val KEY_F15: OmniKey = OmniKey(GLFW.GLFW_KEY_F15)

    // --- Modifiers ---
    @JvmField public val KEY_LEFT_SHIFT: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT_SHIFT)
    @JvmField public val KEY_RIGHT_SHIFT: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT_SHIFT)
    @JvmField public val KEY_LEFT_CONTROL: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT_CONTROL)
    @JvmField public val KEY_RIGHT_CONTROL: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT_CONTROL)
    @JvmField public val KEY_LEFT_ALT: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT_ALT)
    @JvmField public val KEY_RIGHT_ALT: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT_ALT)
    @JvmField public val KEY_LEFT_SUPER: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT_SUPER)
    @JvmField public val KEY_RIGHT_SUPER: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT_SUPER)
    @JvmField public val KEY_CAPS_LOCK: OmniKey = OmniKey(GLFW.GLFW_KEY_CAPS_LOCK)
    @JvmField public val KEY_NUM_LOCK: OmniKey = OmniKey(GLFW.GLFW_KEY_NUM_LOCK)
    @JvmField public val KEY_SCROLL_LOCK: OmniKey = OmniKey(GLFW.GLFW_KEY_SCROLL_LOCK)

    // --- Control / Editing ---
    @JvmField public val KEY_TAB: OmniKey = OmniKey(GLFW.GLFW_KEY_TAB)
    @JvmField public val KEY_ENTER: OmniKey = OmniKey(GLFW.GLFW_KEY_ENTER)
    @JvmField public val KEY_BACKSPACE: OmniKey = OmniKey(GLFW.GLFW_KEY_BACKSPACE)
    @JvmField public val KEY_DELETE: OmniKey = OmniKey(GLFW.GLFW_KEY_DELETE)
    @JvmField public val KEY_INSERT: OmniKey = OmniKey(GLFW.GLFW_KEY_INSERT)
    @JvmField public val KEY_PAGE_UP: OmniKey = OmniKey(GLFW.GLFW_KEY_PAGE_UP)
    @JvmField public val KEY_PAGE_DOWN: OmniKey = OmniKey(GLFW.GLFW_KEY_PAGE_DOWN)
    @JvmField public val KEY_HOME: OmniKey = OmniKey(GLFW.GLFW_KEY_HOME)
    @JvmField public val KEY_END: OmniKey = OmniKey(GLFW.GLFW_KEY_END)

    // --- Arrows ---
    @JvmField public val KEY_LEFT: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT)
    @JvmField public val KEY_RIGHT: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT)
    @JvmField public val KEY_UP: OmniKey = OmniKey(GLFW.GLFW_KEY_UP)
    @JvmField public val KEY_DOWN: OmniKey = OmniKey(GLFW.GLFW_KEY_DOWN)

    // --- Numbers / Letters ---
    @JvmField public val KEY_0: OmniKey = OmniKey(GLFW.GLFW_KEY_0)
    @JvmField public val KEY_1: OmniKey = OmniKey(GLFW.GLFW_KEY_1)
    @JvmField public val KEY_2: OmniKey = OmniKey(GLFW.GLFW_KEY_2)
    @JvmField public val KEY_3: OmniKey = OmniKey(GLFW.GLFW_KEY_3)
    @JvmField public val KEY_4: OmniKey = OmniKey(GLFW.GLFW_KEY_4)
    @JvmField public val KEY_5: OmniKey = OmniKey(GLFW.GLFW_KEY_5)
    @JvmField public val KEY_6: OmniKey = OmniKey(GLFW.GLFW_KEY_6)
    @JvmField public val KEY_7: OmniKey = OmniKey(GLFW.GLFW_KEY_7)
    @JvmField public val KEY_8: OmniKey = OmniKey(GLFW.GLFW_KEY_8)
    @JvmField public val KEY_9: OmniKey = OmniKey(GLFW.GLFW_KEY_9)

    @JvmField public val KEY_A: OmniKey = OmniKey(GLFW.GLFW_KEY_A)
    @JvmField public val KEY_B: OmniKey = OmniKey(GLFW.GLFW_KEY_B)
    @JvmField public val KEY_C: OmniKey = OmniKey(GLFW.GLFW_KEY_C)
    @JvmField public val KEY_D: OmniKey = OmniKey(GLFW.GLFW_KEY_D)
    @JvmField public val KEY_E: OmniKey = OmniKey(GLFW.GLFW_KEY_E)
    @JvmField public val KEY_F: OmniKey = OmniKey(GLFW.GLFW_KEY_F)
    @JvmField public val KEY_G: OmniKey = OmniKey(GLFW.GLFW_KEY_G)
    @JvmField public val KEY_H: OmniKey = OmniKey(GLFW.GLFW_KEY_H)
    @JvmField public val KEY_I: OmniKey = OmniKey(GLFW.GLFW_KEY_I)
    @JvmField public val KEY_J: OmniKey = OmniKey(GLFW.GLFW_KEY_J)
    @JvmField public val KEY_K: OmniKey = OmniKey(GLFW.GLFW_KEY_K)
    @JvmField public val KEY_L: OmniKey = OmniKey(GLFW.GLFW_KEY_L)
    @JvmField public val KEY_M: OmniKey = OmniKey(GLFW.GLFW_KEY_M)
    @JvmField public val KEY_N: OmniKey = OmniKey(GLFW.GLFW_KEY_N)
    @JvmField public val KEY_O: OmniKey = OmniKey(GLFW.GLFW_KEY_O)
    @JvmField public val KEY_P: OmniKey = OmniKey(GLFW.GLFW_KEY_P)
    @JvmField public val KEY_Q: OmniKey = OmniKey(GLFW.GLFW_KEY_Q)
    @JvmField public val KEY_R: OmniKey = OmniKey(GLFW.GLFW_KEY_R)
    @JvmField public val KEY_S: OmniKey = OmniKey(GLFW.GLFW_KEY_S)
    @JvmField public val KEY_T: OmniKey = OmniKey(GLFW.GLFW_KEY_T)
    @JvmField public val KEY_U: OmniKey = OmniKey(GLFW.GLFW_KEY_U)
    @JvmField public val KEY_V: OmniKey = OmniKey(GLFW.GLFW_KEY_V)
    @JvmField public val KEY_W: OmniKey = OmniKey(GLFW.GLFW_KEY_W)
    @JvmField public val KEY_X: OmniKey = OmniKey(GLFW.GLFW_KEY_X)
    @JvmField public val KEY_Y: OmniKey = OmniKey(GLFW.GLFW_KEY_Y)
    @JvmField public val KEY_Z: OmniKey = OmniKey(GLFW.GLFW_KEY_Z)

    // --- Symbols ---
    @JvmField public val KEY_SPACE: OmniKey = OmniKey(GLFW.GLFW_KEY_SPACE)
    @JvmField public val KEY_APOSTROPHE: OmniKey = OmniKey(GLFW.GLFW_KEY_APOSTROPHE)
    @JvmField public val KEY_COMMA: OmniKey = OmniKey(GLFW.GLFW_KEY_COMMA)
    @JvmField public val KEY_MINUS: OmniKey = OmniKey(GLFW.GLFW_KEY_MINUS)
    @JvmField public val KEY_PERIOD: OmniKey = OmniKey(GLFW.GLFW_KEY_PERIOD)
    @JvmField public val KEY_SLASH: OmniKey = OmniKey(GLFW.GLFW_KEY_SLASH)
    @JvmField public val KEY_SEMICOLON: OmniKey = OmniKey(GLFW.GLFW_KEY_SEMICOLON)
    @JvmField public val KEY_EQUAL: OmniKey = OmniKey(GLFW.GLFW_KEY_EQUAL)
    @JvmField public val KEY_LEFT_BRACKET: OmniKey = OmniKey(GLFW.GLFW_KEY_LEFT_BRACKET)
    @JvmField public val KEY_BACKSLASH: OmniKey = OmniKey(GLFW.GLFW_KEY_BACKSLASH)
    @JvmField public val KEY_RIGHT_BRACKET: OmniKey = OmniKey(GLFW.GLFW_KEY_RIGHT_BRACKET)
    @JvmField public val KEY_GRAVE_ACCENT: OmniKey = OmniKey(GLFW.GLFW_KEY_GRAVE_ACCENT)

    // --- Keypad ---
    @JvmField public val KEY_NUMPAD_0: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_0)
    @JvmField public val KEY_NUMPAD_1: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_1)
    @JvmField public val KEY_NUMPAD_2: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_2)
    @JvmField public val KEY_NUMPAD_3: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_3)
    @JvmField public val KEY_NUMPAD_4: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_4)
    @JvmField public val KEY_NUMPAD_5: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_5)
    @JvmField public val KEY_NUMPAD_6: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_6)
    @JvmField public val KEY_NUMPAD_7: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_7)
    @JvmField public val KEY_NUMPAD_8: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_8)
    @JvmField public val KEY_NUMPAD_9: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_9)

    @JvmField public val KEY_NUMPAD_DECIMAL: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_DECIMAL)
    @JvmField public val KEY_NUMPAD_DIVIDE: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_DIVIDE)
    @JvmField public val KEY_NUMPAD_MULTIPLY: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_MULTIPLY)
    @JvmField public val KEY_NUMPAD_SUBTRACT: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_SUBTRACT)
    @JvmField public val KEY_NUMPAD_ADD: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_ADD)
    @JvmField public val KEY_NUMPAD_ENTER: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_ENTER)
    @JvmField public val KEY_NUMPAD_EQUAL: OmniKey = OmniKey(GLFW.GLFW_KEY_KP_EQUAL)

    // --- Miscellaneous ---
    @JvmField public val KEY_PRINT_SCREEN: OmniKey = OmniKey(GLFW.GLFW_KEY_PRINT_SCREEN)
    @JvmField public val KEY_PAUSE: OmniKey = OmniKey(GLFW.GLFW_KEY_PAUSE)
    @JvmField public val KEY_MENU: OmniKey = OmniKey(GLFW.GLFW_KEY_MENU)
}
