package dev.deftu.omnicore.api.client.input

import org.lwjgl.input.Keyboard

public object OmniKeys {
    // --- Special / Unknown ---
    @JvmField public val KEY_NONE: OmniKey = OmniKey(Keyboard.KEY_NONE)

    // --- Function Keys ---
    @JvmField public val KEY_ESCAPE: OmniKey = OmniKey(Keyboard.KEY_ESCAPE)
    @JvmField public val KEY_F1: OmniKey = OmniKey(Keyboard.KEY_F1)
    @JvmField public val KEY_F2: OmniKey = OmniKey(Keyboard.KEY_F2)
    @JvmField public val KEY_F3: OmniKey = OmniKey(Keyboard.KEY_F3)
    @JvmField public val KEY_F4: OmniKey = OmniKey(Keyboard.KEY_F4)
    @JvmField public val KEY_F5: OmniKey = OmniKey(Keyboard.KEY_F5)
    @JvmField public val KEY_F6: OmniKey = OmniKey(Keyboard.KEY_F6)
    @JvmField public val KEY_F7: OmniKey = OmniKey(Keyboard.KEY_F7)
    @JvmField public val KEY_F8: OmniKey = OmniKey(Keyboard.KEY_F8)
    @JvmField public val KEY_F9: OmniKey = OmniKey(Keyboard.KEY_F9)
    @JvmField public val KEY_F10: OmniKey = OmniKey(Keyboard.KEY_F10)
    @JvmField public val KEY_F11: OmniKey = OmniKey(Keyboard.KEY_F11)
    @JvmField public val KEY_F12: OmniKey = OmniKey(Keyboard.KEY_F12)
    @JvmField public val KEY_F13: OmniKey = OmniKey(Keyboard.KEY_F13)
    @JvmField public val KEY_F14: OmniKey = OmniKey(Keyboard.KEY_F14)
    @JvmField public val KEY_F15: OmniKey = OmniKey(Keyboard.KEY_F15)

    // --- Modifiers ---
    @JvmField public val KEY_LEFT_SHIFT: OmniKey = OmniKey(Keyboard.KEY_LSHIFT)
    @JvmField public val KEY_RIGHT_SHIFT: OmniKey = OmniKey(Keyboard.KEY_RSHIFT)
    @JvmField public val KEY_LEFT_CONTROL: OmniKey = OmniKey(Keyboard.KEY_LCONTROL)
    @JvmField public val KEY_RIGHT_CONTROL: OmniKey = OmniKey(Keyboard.KEY_RCONTROL)
    @JvmField public val KEY_LEFT_ALT: OmniKey = OmniKey(Keyboard.KEY_LMENU)
    @JvmField public val KEY_RIGHT_ALT: OmniKey = OmniKey(Keyboard.KEY_RMENU)
    @JvmField public val KEY_LEFT_SUPER: OmniKey = OmniKey(Keyboard.KEY_LMETA)
    @JvmField public val KEY_RIGHT_SUPER: OmniKey = OmniKey(Keyboard.KEY_RMETA)
    @JvmField public val KEY_CAPS_LOCK: OmniKey = OmniKey(Keyboard.KEY_CAPITAL)
    @JvmField public val KEY_NUM_LOCK: OmniKey = OmniKey(Keyboard.KEY_NUMLOCK)
    @JvmField public val KEY_SCROLL_LOCK: OmniKey = OmniKey(Keyboard.KEY_SCROLL)

    // --- Control / Editing ---
    @JvmField public val KEY_TAB: OmniKey = OmniKey(Keyboard.KEY_TAB)
    @JvmField public val KEY_ENTER: OmniKey = OmniKey(Keyboard.KEY_RETURN)
    @JvmField public val KEY_BACKSPACE: OmniKey = OmniKey(Keyboard.KEY_BACK)
    @JvmField public val KEY_DELETE: OmniKey = OmniKey(Keyboard.KEY_DELETE)
    @JvmField public val KEY_INSERT: OmniKey = OmniKey(Keyboard.KEY_INSERT)
    @JvmField public val KEY_PAGE_UP: OmniKey = OmniKey(Keyboard.KEY_PRIOR)
    @JvmField public val KEY_PAGE_DOWN: OmniKey = OmniKey(Keyboard.KEY_NEXT)
    @JvmField public val KEY_HOME: OmniKey = OmniKey(Keyboard.KEY_HOME)
    @JvmField public val KEY_END: OmniKey = OmniKey(Keyboard.KEY_END)

    // --- Arrows ---
    @JvmField public val KEY_LEFT: OmniKey = OmniKey(Keyboard.KEY_LEFT)
    @JvmField public val KEY_RIGHT: OmniKey = OmniKey(Keyboard.KEY_RIGHT)
    @JvmField public val KEY_UP: OmniKey = OmniKey(Keyboard.KEY_UP)
    @JvmField public val KEY_DOWN: OmniKey = OmniKey(Keyboard.KEY_DOWN)

    // --- Numbers / Letters ---
    @JvmField public val KEY_0: OmniKey = OmniKey(Keyboard.KEY_0)
    @JvmField public val KEY_1: OmniKey = OmniKey(Keyboard.KEY_1)
    @JvmField public val KEY_2: OmniKey = OmniKey(Keyboard.KEY_2)
    @JvmField public val KEY_3: OmniKey = OmniKey(Keyboard.KEY_3)
    @JvmField public val KEY_4: OmniKey = OmniKey(Keyboard.KEY_4)
    @JvmField public val KEY_5: OmniKey = OmniKey(Keyboard.KEY_5)
    @JvmField public val KEY_6: OmniKey = OmniKey(Keyboard.KEY_6)
    @JvmField public val KEY_7: OmniKey = OmniKey(Keyboard.KEY_7)
    @JvmField public val KEY_8: OmniKey = OmniKey(Keyboard.KEY_8)
    @JvmField public val KEY_9: OmniKey = OmniKey(Keyboard.KEY_9)

    @JvmField public val KEY_A: OmniKey = OmniKey(Keyboard.KEY_A)
    @JvmField public val KEY_B: OmniKey = OmniKey(Keyboard.KEY_B)
    @JvmField public val KEY_C: OmniKey = OmniKey(Keyboard.KEY_C)
    @JvmField public val KEY_D: OmniKey = OmniKey(Keyboard.KEY_D)
    @JvmField public val KEY_E: OmniKey = OmniKey(Keyboard.KEY_E)
    @JvmField public val KEY_F: OmniKey = OmniKey(Keyboard.KEY_F)
    @JvmField public val KEY_G: OmniKey = OmniKey(Keyboard.KEY_G)
    @JvmField public val KEY_H: OmniKey = OmniKey(Keyboard.KEY_H)
    @JvmField public val KEY_I: OmniKey = OmniKey(Keyboard.KEY_I)
    @JvmField public val KEY_J: OmniKey = OmniKey(Keyboard.KEY_J)
    @JvmField public val KEY_K: OmniKey = OmniKey(Keyboard.KEY_K)
    @JvmField public val KEY_L: OmniKey = OmniKey(Keyboard.KEY_L)
    @JvmField public val KEY_M: OmniKey = OmniKey(Keyboard.KEY_M)
    @JvmField public val KEY_N: OmniKey = OmniKey(Keyboard.KEY_N)
    @JvmField public val KEY_O: OmniKey = OmniKey(Keyboard.KEY_O)
    @JvmField public val KEY_P: OmniKey = OmniKey(Keyboard.KEY_P)
    @JvmField public val KEY_Q: OmniKey = OmniKey(Keyboard.KEY_Q)
    @JvmField public val KEY_R: OmniKey = OmniKey(Keyboard.KEY_R)
    @JvmField public val KEY_S: OmniKey = OmniKey(Keyboard.KEY_S)
    @JvmField public val KEY_T: OmniKey = OmniKey(Keyboard.KEY_T)
    @JvmField public val KEY_U: OmniKey = OmniKey(Keyboard.KEY_U)
    @JvmField public val KEY_V: OmniKey = OmniKey(Keyboard.KEY_V)
    @JvmField public val KEY_W: OmniKey = OmniKey(Keyboard.KEY_W)
    @JvmField public val KEY_X: OmniKey = OmniKey(Keyboard.KEY_X)
    @JvmField public val KEY_Y: OmniKey = OmniKey(Keyboard.KEY_Y)
    @JvmField public val KEY_Z: OmniKey = OmniKey(Keyboard.KEY_Z)

    // --- Symbols ---
    @JvmField public val KEY_SPACE: OmniKey = OmniKey(Keyboard.KEY_SPACE)
    @JvmField public val KEY_APOSTROPHE: OmniKey = OmniKey(Keyboard.KEY_APOSTROPHE)
    @JvmField public val KEY_COMMA: OmniKey = OmniKey(Keyboard.KEY_COMMA)
    @JvmField public val KEY_MINUS: OmniKey = OmniKey(Keyboard.KEY_MINUS)
    @JvmField public val KEY_PERIOD: OmniKey = OmniKey(Keyboard.KEY_PERIOD)
    @JvmField public val KEY_SLASH: OmniKey = OmniKey(Keyboard.KEY_SLASH)
    @JvmField public val KEY_SEMICOLON: OmniKey = OmniKey(Keyboard.KEY_SEMICOLON)
    @JvmField public val KEY_EQUAL: OmniKey = OmniKey(Keyboard.KEY_EQUALS)
    @JvmField public val KEY_LEFT_BRACKET: OmniKey = OmniKey(Keyboard.KEY_LBRACKET)
    @JvmField public val KEY_BACKSLASH: OmniKey = OmniKey(Keyboard.KEY_BACKSLASH)
    @JvmField public val KEY_RIGHT_BRACKET: OmniKey = OmniKey(Keyboard.KEY_RBRACKET)
    @JvmField public val KEY_GRAVE_ACCENT: OmniKey = OmniKey(Keyboard.KEY_GRAVE)

    // --- Keypad ---
    @JvmField public val KEY_NUMPAD_0: OmniKey = OmniKey(Keyboard.KEY_NUMPAD0)
    @JvmField public val KEY_NUMPAD_1: OmniKey = OmniKey(Keyboard.KEY_NUMPAD1)
    @JvmField public val KEY_NUMPAD_2: OmniKey = OmniKey(Keyboard.KEY_NUMPAD2)
    @JvmField public val KEY_NUMPAD_3: OmniKey = OmniKey(Keyboard.KEY_NUMPAD3)
    @JvmField public val KEY_NUMPAD_4: OmniKey = OmniKey(Keyboard.KEY_NUMPAD4)
    @JvmField public val KEY_NUMPAD_5: OmniKey = OmniKey(Keyboard.KEY_NUMPAD5)
    @JvmField public val KEY_NUMPAD_6: OmniKey = OmniKey(Keyboard.KEY_NUMPAD6)
    @JvmField public val KEY_NUMPAD_7: OmniKey = OmniKey(Keyboard.KEY_NUMPAD7)
    @JvmField public val KEY_NUMPAD_8: OmniKey = OmniKey(Keyboard.KEY_NUMPAD8)
    @JvmField public val KEY_NUMPAD_9: OmniKey = OmniKey(Keyboard.KEY_NUMPAD9)

    @JvmField public val KEY_NUMPAD_DECIMAL: OmniKey = OmniKey(Keyboard.KEY_DECIMAL)
    @JvmField public val KEY_NUMPAD_DIVIDE: OmniKey = OmniKey(Keyboard.KEY_DIVIDE)
    @JvmField public val KEY_NUMPAD_MULTIPLY: OmniKey = OmniKey(Keyboard.KEY_MULTIPLY)
    @JvmField public val KEY_NUMPAD_SUBTRACT: OmniKey = OmniKey(Keyboard.KEY_SUBTRACT)
    @JvmField public val KEY_NUMPAD_ADD: OmniKey = OmniKey(Keyboard.KEY_ADD)
    @JvmField public val KEY_NUMPAD_ENTER: OmniKey = OmniKey(Keyboard.KEY_NUMPADENTER)
    @JvmField public val KEY_NUMPAD_EQUAL: OmniKey = OmniKey(Keyboard.KEY_NUMPADEQUALS)

    // --- Miscellaneous ---
    @JvmField public val KEY_PRINT_SCREEN: OmniKey = OmniKey(Keyboard.KEY_SYSRQ)
    @JvmField public val KEY_PAUSE: OmniKey = OmniKey(Keyboard.KEY_PAUSE)
    @JvmField public val KEY_MENU: OmniKey = OmniKey(Keyboard.KEY_APPS)
}
